# Generated by Django 5.0.3 on 2024-05-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='moisture',
            new_name='moisture_percentage',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='moisture_value',
            field=models.FloatField(default=0.0),
        ),
    ]
