# Generated by Django 5.0.3 on 2024-06-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0002_rename_moisture_sensordata_moisture_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='motor_status',
            field=models.CharField(default='Unknown state', max_length=20),
        ),
    ]
